sudo: required
dist: trusty

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  
before_script:
  - args=()
  - if [ "$HAXE_VERSION" == "latest" ]; then args+=(-lib); args+=(hx3compat); fi

script:
  - lix run travix interp "${args[@]}"
  - lix run travix neko "${args[@]}"
  #- lix run travix python "${args[@]}"
  - lix run travix node "${args[@]}"
  # - lix run travix flash "${args[@]}"
  - lix run travix java "${args[@]}"
  #- lix run travix cpp "${args[@]}"
  #- lix run travix cs "${args[@]}"
  - lix run travix php "${args[@]}"
